### ISSUE TITLE
Standardized correlation error

### ISSUE THREAD

**Issue by BTunca** [dr-JT/semoutput#2]
Hi again!

I was running a two factor model and noticed that the sem.factorcor function returns the nonstandardized coefficient. I tried with and without the "standardized" argument:

sem.factorcor(fit, factors = factors, standardized = TRUE)

Here are the outputs from the sem.factorcor, lavaan summary function, and the semplot. I wonder if it is a two-factor issue because in your example it works fine.

Thanks for the help!

All best,
Burak

![screenshot_2](https://user-images.githubusercontent.com/27208030/45376132-5b69a580-b5f7-11e8-8d15-0e8d78d7f243.png)
![screenshot_1](https://user-images.githubusercontent.com/27208030/45376133-5b69a580-b5f7-11e8-9bc8-ccf883f7f689.png)

**Comment by dr-JT** [comment]
Yep you are right, I had it reporting the unstandardized estimates. In my example the standardized and unstandardized estimates were equivalent because I set the factor variances to be equal to 1.

I have made the changes so that it should report the standardized estimate now. Let me know if it works for you.

Thanks for catching this!

**Comment by BTunca** [comment]
Thank you works great!
